### ISSUE TITLE
[Docker] Config directory should be on the host as a volume to persist

### ISSUE THREAD

**Issue by ponchohoncho** [aunefyren/plex-wrapped#13]
Hello! This is a very very cool project!

When I try to put the config directory into an external volume, your container can't read it. 

I put this in my compose yaml

```
#    volumes:
#      - ./plex-wrapped/config:/var/www/html/config
```

But then the server setup and account creation sections don't load. When I set it up with the recommended docker config, it came right up. But if the container is recreated, then all the settings are lost. By placing the config files on an external volume, then they can persist even when the container is recreated.

**Comment by aunefyren** [comment]
Hey, you are on the right path, good job! The reason the UI freaks out is because it can't access the config folder. This is because it is now a directory that belongs to you, the Docker host. The docker image tries to chmod it, but is not allowed, so you have to do it from the host. Simply doing `$ sudo chmod 777 ./plex-wrapped/config` should do the trick.
